apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "document-extraction.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "document-extraction.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
